# This file contains values from Cookiecutter

default_context:
  project_name: "cookbooks"
  project_description: "`cookbooks` is a Python cli/package to work with TAPIS to build cookbook"
  organization: "In-For-Disaster-Analytics"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "In-For-Disaster-Analytics"
  email: "maxiosorio@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
